name: Basic Hello world program with few extra steps
on: [push, pull_request]
jobs:
  my-job:
    runs-on: macos-latest
    steps:
      - name: Clone the git repo
        uses: actions/checkout@v3
      - name: Build the code
        run: |
          make -j2
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./prog
